markdown: kramdown
highlighter: rouge

permalink: pretty

# Site info
title: Rohan Khan
tagline: "Bioinformatics & Genomics"
description: "Bioinformatician at CCM, SickKids"
url: "https://rohan-ah-khan.github.io"  
baseurl: ""                              

author:
  name: "Rohan Khan"
  url: "https://rohan-ah-khan.github.io"

paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-paginate

version: "2.1.0"

github:
  repo: "https://github.com/rohan-ah-khan/rohan-ah-khan.github.io"
